config/routes.rb
Rails.application.routes.draw do
  resources :todos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
      @todo = Todo.new(todo_params)
      @todo.save
      redirect_to todos_path
  end

def show
  @todo = Todo.find(params[:id])
end

def edit
  @todo = Todo.find(params[:id])
end

def update
  @todo = Todo.find(params[:id])
  @todo.update(todo_params)
  redirect_to todos_path
end

def destroy
  @todo = Todo.find(params[:id])
  @todo.destroy
  redirect_to todos_path
end

def validation
  @todo = Todo.find(params[:id])
  @todo.where(completed:true)
  redirect_to todos_path
end


  private

  def todo_params
  params.require(:todo).permit(:description, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoAp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>


<div>


    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">To Do</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="<%= todos_path %>">Index <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=" <%= new_todo_path %> ">New</a>
          </li>
        </ul>
      </div>
    </nav>
</div>

    <%= yield %>
  </body>



</html>

app/views/todos/_form.html.erb
<div class = "margintop">
  <h1>Formulario</h1>
  <div class="well">
    <fieldset>
    <%= form_with model: @todo, local: true do |form| %>
    <%= form.label :description, "To Do" %>
    <%= form.text_field :description %>
    <%= form.label :completed, "Contenido" %>
    <%= form.text_field :completed %>
    <%=form.submit "Crear" %>
    <% end %>
    </fieldset>
  </div>
</div>

app/views/todos/edit.html.erb
<%= render 'todos/form' %>

app/views/todos/index.html.erb
<div class = "margintop">
<% @todos.each do |todo| %>
<h1>  <%= link_to todo.description, todo %> </h1>
<p>  <%= todo.completed %> </p>
<p>  <%= link_to "Borrar", todo, method: :delete%> </p>
<% end %>
</div>

app/views/todos/new.html.erb
<%= render 'todos/form' %>

app/views/todos/show.html.erb
<div class="margintop">


<h1> <%= @todo.description %> </h1>
<p> <%= @todo.completed %> </p>
<p> creado hace: <%= @todo.created_at %> </p>

</div>